### PR TITLE
Drawing tools facelift

### PR DESCRIPTION
**Pull request by sgriffin231**
A few changes to the gameplay control section and the css to make the radio buttons look like regular buttons. Four pngs in "thicknesses" folder within the images directory have been added.

### CODE REVIEW

**Comment by melindamorang** [comment]
Hiiiii.

So I noticed that the white card surrounding the drawing is missing now when in gameplay text mode.  This is a problem because erasures are actually white lines...
image

Can you please fix this before we merge?

**Comment by melindamorang** [comment]
(Applies to the endgame page as well.

**Comment by sgriffin231** [comment]
Got it. I also want to incorporate the new green selection outlines I'm
about to send you in this round, since I realized I forgot to give any hint
which size you had selected.

**Comment by sgriffin231** [comment]
K. Updated.

**Pull request closed without merging**
