### PR TITLE
Update for graphics tablets

### PR DESCRIPTION
**Pull request by sgriffin231**
Jacob changed events and fixed line creation when clicking off canvas. (He needs a new invite to the repository.)

### CODE REVIEW

**Comment by melindamorang** [comment]
This branch is live right now. Please give it a whirl.

**Comment by sgriffin231** [comment]
You have an iPhone, right? I have an iPad around here somewhere that I forgot to return to Jessica.

**Comment by melindamorang** [comment]
Nope, mine's an Android. I have a work friend I bother every time I need an iPhone test.

**Comment by sgriffin231** [comment]
lol. If this works, I'll see if Michelle A can try it out. Who else had
problems?

**Comment by melindamorang** [comment]
One of my college friends had issues with a hacked Kindle Fire, but I kind of gave up on that one.

**Comment by sgriffin231** [comment]
Who is seriously going to spend time trying to accommodate a hacked Kindle
Fire??? I have a feeling this isn't the only problem he had.

**Comment by sgriffin231** [comment]
IT WORKS!!!! Ready to close. Just FYI: The time between when I asked Jacob to look at it to when he emailed me the fix for TWO problems was 16 minutes.

**Comment by melindamorang** [comment]
Awesome! I should ask him to fix stuff more often.  I'm going to get my iPhone friend to test it before merging just in case.

**Comment by melindamorang** [comment]
:( :( :(
My iPhone friend says this change makes it so he can no longer draw dots. That's the problem I was having earlier when testing a similar fix.

I was thinking the issue was that the iPhone is registering the pointer events in addition to the touch events, whereas it doesn't register mouse events. The pointer events don't trigger this part:

```javascript
if (mouseEvent.type == "touchstart") {
    mouseEvent = mouseEvent.touches[0];
```

I went down a rabbithole on that earlier and got nowhere because I couldn't even tell if that was really the problem.

**Comment by sgriffin231** [comment]
I'll send to Jacob.

**Comment by melindamorang** [comment]
Jacob's latest fix involves removing all the touch listeners and just relying on pointer listeners. I'll push these live and test them before merging to master.

**Comment by melindamorang** [comment]
Ughghghgh. My iPhone colleague says he still can't draw dots with this latest version.

**Comment by sgriffin231** [comment]
Will try again in May. :(

**Pull request closed without merging**
