### PR TITLE
Fixed so the text will wrap

### PR DESCRIPTION
**Pull request by sgriffin231**
I can make it prettier later. I wanted to get this one done for function first.

### CODE REVIEW

**Review by melindamorang — COMMENTED** [review]
This looks like the same branch as the Clear button one, not a text wrapping change.  Check in the wrong branch maybe?

**Comment by sgriffin231** [comment]
> This looks like the same branch as the Clear button one, not a text wrapping change. Check in the wrong branch maybe?

There should be a small difference in gameplay.php.

**Comment by melindamorang** [comment]
Okay, so this PR has both changes (Clear button/formatting and text wrapping)?  In that case, I suggest you scrap the other PR since we don't need it, then clean up this one (fix the database info and .gitignore), and then we'll merge this one.

**Comment by melindamorang** [comment]
The text wrapping and clear button stuff work great, though!

**Review by melindamorang — CHANGES_REQUESTED** [review]
Remove open-database-connection.php from .gitignore and restore the database connection info to the one needed for our host's servers.

**Comment by sgriffin231** [comment]
> Remove open-database-connection.php from .gitignore and restore the database connection info to the one needed for our host's servers.

I thought the whole point of having a gitignore was to make sure those changes are not saved. I cannot change my local copy, or I won't be able to test stuff.

**Comment by melindamorang** [comment]
You shouldn't ignore a file that is a required component of the program, though, and that's the problem I see here.

Some possible solutions:
1) Update your local database and connection info to match that stored in the file (that's what I've done - don't know how this is done on MAMP).
2) Update the way this file works so that it's like this:
  a) The existing file stays as it is with the connection info configured to work with the version on the server
  b) Add an additional file (like a config file) with variables that can override the connection info.
  c) Add the new config file to .gitignore so it's not tracked in the repo.
  c) Make the original file import the values from the config file if it's present. Otherwise, use the defaults in the original file.
  We have some python files at work that work this way, and it's easy to do. I don't know how to do this in php, though. I can look it up later if you haven't found a solution yet.

**Pull request closed without merging**
