### PR TITLE
CSS 2 plus organization

### PR DESCRIPTION
**Pull request by sgriffin231**
- Moved around details and edited size on the results pages
- Created cards around endgame text
- Made player's stack being viewed orange
- Removed new game button
- Resizes type size if too long on endgame card
- Fixed centering on player buttons on end screen

### CODE REVIEW

**Comment by melindamorang** [comment]
This looks good, except one thing. Why is the Clear button now a radio button?
image

**Comment by sgriffin231** [comment]
So it looks like one of the tools and not the submit button. :)

**Comment by melindamorang** [comment]
But it's weird because it still functions like a radio button and preserves its state. It makes it look like an option is either selected or deselected. In the screenshot above, I had clicked it once to clear everything, and now it looks like I'm in "Erase All" mode or something.  Can we make it a real button, but not a super obvious button?

**Comment by sgriffin231** [comment]
Maybe I'll make it a red circle with an X in it and a title that pops up
with "delete all."

Can you move over the new images folder? There's a broken link instead of
the logo.

**Comment by sgriffin231** [comment]
Actually, it looks like it might be a structure issue. I'll fix it.

**Comment by melindamorang** [comment]
Oh, I see what you mean about the broken logo image. There was no problem when I tested locally, but the live version on the server is broken.  Please fix that in a separate pull request, as that problem is unrelated to the issue we're discussing here with the Clear button format.

**Comment by melindamorang** [comment]
Oh never mind. I see how to fix it. Just needs a better relative path.  I got it.

**Comment by melindamorang** [comment]
Banner logo image is fixed on the live version.

**Review by melindamorang — CHANGES_REQUESTED** [review]
Update Erase All so it isn't a radio button. See comments, and have a nice day. :)

**Comment by melindamorang** [comment]
gd clear button is orange again. Hopefully we can make the gd clear button less orange but also not a radio button in a future update. :)  Merging now.

**Comment by sgriffin231** [comment]
I think I know how to make everyone happy here with the radio buttons and whatnot using Font Awesome and leaving the radio buttons and the link as is. I'll create a new branch just for this.

**Pull request merged**
