### PR TITLE
Canvas control buttons

### PR DESCRIPTION
**Pull request by sgriffin231**

### CODE REVIEW

**Comment by melindamorang** [comment]
Is it intentional that the hover behavior for the "See results of a completed game" button is that the button color goes clear or matches the light blue background. Seems a bit weird.
image

**Comment by melindamorang** [comment]
Seems to be an issue with most buttons.

**Comment by melindamorang** [comment]
Otherwise it looks really nice. Let me know if you want to fix that. If not, I can go ahead and merge this as is since everything is working.

**Comment by sgriffin231** [comment]
omfg. I tested every page but the home page. Ugh. One moment please.

**Comment by sgriffin231** [comment]
Okay, try it again.

**Comment by melindamorang** [comment]
Looks good.

**Comment by sgriffin231** [comment]
Woot!

**Comment by melindamorang** [comment]
Changes are live

**Pull request merged**
