### PR TITLE
Clear button, text area changes

### PR DESCRIPTION
**Pull request by sgriffin231**
I think this is everything we talked about.

### CODE REVIEW

**Comment by melindamorang** [comment]
Seemed like the .gitignore was not updated the way we discussed, so I made the change.  I also made it ignore the Mac auto-generated .DS_Store file that accidentally got checked in, and I deleted some other weird binary file garbage that shouldn't have been in here.

**Comment by melindamorang** [comment]
Okay, I'm gonna merge it. Then I'm gonna make the site work right.

**Comment by sgriffin231** [comment]
Sorry. I thought I'd figured out the buttons to push last night, but
apparently I didn't. Once you're done with this, I'm going to delete all of
my branches and freshen up my local files. If I have to redo something, so
be it.

**Comment by melindamorang** [comment]
I'm done with this branch, although I am not completely convinced that I have done the right thing on the server so that the next update won't nuke the database connection info again.  I will figure it out at that point, though.  For now, the site is working with your updates.

**Comment by melindamorang** [comment]
The changes to .gitignore did not cause the existing file to stop tracking changes locally for me.  Doing this in my local git command line worked: https://stackoverflow.com/questions/1274057/how-to-make-git-forget-about-a-file-that-was-tracked-but-is-now-in-gitignore/20241145#20241145

However, this seems to be a local setting and not a repo setting, so I don't know quite how to make it so any clone will end up in that state. I also don't know how to make the server get in that state.  Working on it...

**Comment by melindamorang** [comment]
Ughghghg. I have another idea about how to solve this (basically returning to my original idea about importing an ignored file only if it exists).  I will experiment with it this weekend and see if I can get it to work.

**Comment by sgriffin231** [comment]
Do you want to do that, or do you want me to ask my brother? lol
If he does any git, he probably does it through some sort of console,
though, so we might get the code back instead. lol

**Comment by melindamorang** [comment]
Haha, you clearly have great confidence in my abilities.

I think my idea is going to work, and it will only take me about half an hour to try it out.  I just didn't want to do it a few hours before we have a game scheduled just in case.

If it doesn't work, we can ask Greg.

**Pull request merged**
